### PR TITLE
[-v] rds filter/action - filter storage metrics, resize

### PR DESCRIPTION
**Pull request by whit537**
Verbose log for https://github.com/capitalone/cloud-custodian/issues/934.

### Todo

- [ ] test or three for `attr-multiplier` in metrics filter
- [x] ~~implement `FreeStorageSpace` metric~~ https://github.com/whit537/cloud-custodian/pull/11#issuecomment-289364805
- [x] test and implementation for [resizing up](https://github.com/capitalone/cloud-custodian/blob/846cd10aa546a9bc652c8489bf550ba03d77c6c3/c7n/resources/rds.py#L665-L682)
- [ ] test and implementation for [resizing down](https://github.com/capitalone/cloud-custodian/blob/846cd10aa546a9bc652c8489bf550ba03d77c6c3/c7n/resources/rds.py#L685-L703)
- [ ] expose async/immediate to config

### CODE REVIEW

**Comment by whit537** [comment]
Alright, I guess write a test? `tests/test_rds.py` passing locally as it stands ...

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/blob/846cd10aa546a9bc652c8489bf550ba03d77c6c3/tests/test_rds.py#L495-L497

https://www.youtube.com/watch?v=07Y0cy-nvAg 😜

**Comment by kapilt** [comment]
yeah that was for when i was creating it and wanted to wait for rds creation (like 15m).

**Comment by whit537** [comment]
What even is RDS? Hmm ... :thinking:

**Comment by whit537** [comment]
From the console:

> Amazon Relational Database Service (RDS) is a web service that makes it easy to set up, operate, and scale a relational database in the cloud.

**Comment by whit537** [comment]
Alright, and the task here is to implement ... one thing or two? A filter and an action ... that's two things, right?

**Comment by whit537** [comment]
Existing: http://www.capitalone.io/cloud-custodian/docs/policy/resources/rds.html

**Comment by whit537** [comment]
Current diff less whitespace changes: https://github.com/whit537/cloud-custodian/pull/11/files?w=1.

**Comment by whit537** [comment]
Alright, so it looks like we already have a metrics filter, but it might need some modifications to support the resize action, which is new.

> This will find databases using over 85% of their allocated
> storage, and resize them to have an additional 30% storage
> the resize here is async during the next maintenance.

**Comment by whit537** [comment]
Assuming the `attr-multiplier` modification is all that's needed, diving into test/implementation for resize ...

**Comment by whit537** [comment]
Looks like rds tests generally are not good [functional](https://github.com/capitalone/cloud-custodian/pull/1009) candidates. :o)

**Comment by whit537** [comment]
I suspect we're going to end up with a [`_db_eligible_for_resize`](https://github.com/capitalone/cloud-custodian/blob/846cd10aa546a9bc652c8489bf550ba03d77c6c3/c7n/resources/rds.py#L166-L208).

**Comment by whit537** [comment]
Todo started in description.

**Comment by whit537** [comment]
http://boto3.readthedocs.io/en/latest/reference/services/rds.html#RDS.Client.create_db_instance

**Comment by whit537** [comment]
> For supported combinations of instance class and database engine version, see the documentation.

> Note that not all instance classes are available in all regions for all DB engines.

http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

😖

**Comment by whit537** [comment]
Working with `db.r3.large`. Now `AllocatedStorage` ...

(P.S. No other example of `create_db_instance` in our codebase.)

**Comment by whit537** [comment]
Initial tests in 9f6a494eb79fabb07f36c1a1497a80c83f0f7a2a.

**Comment by whit537** [comment]
Wow. Reddit? 😳

https://www.reddit.com/r/aws/comments/2d1a97/aws_rds_can_we_seamlessly_allocate_more_storage/

**Comment by whit537** [comment]
Phew, back to relatives safety.

http://serverfault.com/questions/613182/downtime-for-increasing-rds-storage

**Comment by whit537** [comment]
Here we go:

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html

**Comment by whit537** [comment]
http://boto3.readthedocs.io/en/latest/reference/services/rds.html#RDS.Client.modify_db_instance

**Comment by whit537** [comment]
Not gonna be _that_ easy. :)

> ClientError: An error occurred (InvalidParameterValue) when calling the ModifyDBInstance operation: Requested storage size (5) cannot be less then the current storage size (10)

**Comment by whit537** [comment]
Of course, this was for the resize *up* case, tinkering ... now:

> InvalidDBInstanceStateFault: An error occurred (InvalidDBInstanceState) when calling the ModifyDBInstance operation: Database instance is not in available state.

**Comment by whit537** [comment]
Just need some time, prolly?

**Comment by whit537** [comment]
Database actions take so long, I'm switching to using a unique id for test instances. Need to figure out filtering on it though ...

**Comment by whit537** [comment]
Alright, I think I'm filtering properly, now hitting another "not in available state" error, db has been in `backing-up` for quite some time now.

**Comment by whit537** [comment]
There it is!

**Comment by whit537** [comment]
Right. So, backing up seriously takes, like, 10 minutes. Can we skip that?

**Comment by whit537** [comment]
Yeah modifying takes a while, too.

**Comment by whit537** [comment]
That was more like 15 minutes.

**Comment by whit537** [comment]
Alright, did a run with 60f032f4ee92a69cab48ca9230956684d7f63123 and it came up 10 != 13. More sleep?

**Comment by whit537** [comment]
More sleep! 💃

screen shot 2017-03-25 at 4 55 16 am

**Comment by whit537** [comment]
Bit of a smarter test in 258486868e3430d3cb1be11a598e2b8ef149e0bd.

**Comment by whit537** [comment]
> Not gonna be _that_ easy. :)
>
>> ClientError: An error occurred (InvalidParameterValue) when calling the ModifyDBInstance operation: Requested storage size (5) cannot be less then the current storage size (10)

Alright ... so are we snapshot/recreate/restoring?

**Comment by whit537** [comment]
[Read replica](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstanceReadReplica.html)?

**Comment by whit537** [comment]
Dialing back out for guidance: https://github.com/capitalone/cloud-custodian/issues/934#issuecomment-289202068.

**Comment by whit537** [comment]
Alright. Actions!

**Comment by whit537** [comment]
Parsing https://github.com/capitalone/cloud-custodian/commit/846cd10aa546a9bc652c8489bf550ba03d77c6c3?w=1 ...

**Comment by whit537** [comment]
`attr-multiplier` looks new and partially implemented, while `FreeStorageSpace` looks new and unimplemented.

**Comment by whit537** [comment]
Alright so `FreeStorageSpace` is a type of metric filter?

**Comment by whit537** [comment]
Oh! `metrics` itself is new!

**Comment by whit537** [comment]
> filter storage metrics

**Comment by whit537** [comment]
[Sike](https://github.com/capitalone/cloud-custodian/blob/7fb6a6dbe536f830319d50acd6f94d90030c1c20/c7n/filters/metrics.py).

**Comment by whit537** [comment]
[`FreeStorageSpace`](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/rds-metricscollected.html)

**Comment by whit537** [comment]
Alright, I'm taking it that 846cd10aa546a9bc652c8489bf550ba03d77c6c3 does what's needed re: metrics. Back to resizing down ...

**Comment by whit537** [comment]
> rds filter/action - find overprovisioned storage, resize

Given the original ticket title, it seems that resizing down is important. 😁

**Comment by whit537** [comment]
Suggestion seems to be not even snapshot, but rather dump/restore.

http://dba.stackexchange.com/questions/27639/aws-rds-mysql-how-do-i-reduce-the-db-size
http://dba.stackexchange.com/questions/24491/how-do-i-reduce-the-database-size-on-aws-rds-mysql
http://stackoverflow.com/questions/36746475/how-to-reduce-storagescale-down-my-rds-instance

**Comment by whit537** [comment]
> We recommend that you use native PostgreSQL database migration tools under the following conditions:
>
>- You have a homogeneous migration, where you are migrating from a database with the same database engine as the target database.
>- You are migrating an entire database.
>- The native tools allow you to migrate your system with minimal downtime.
>
>In most other cases, performing a database migration using AWS Database Migration Service (AWS DMS) is the best approach. AWS DMS can migrate databases without downtime and, for many database engines, continue ongoing replication until you are ready to switch over to the target database. You can migrate to either the same database engine or a different database engine using AWS DMS. If you are migrating to a different database engine than your source database, you can use the AWS Schema Conversion Tool to migrate schema objects that are not migrated by AWS DMS. For more information about AWS DMS, see [What is AWS Database Migration Service]().

**Comment by whit537** [comment]
> AWS DMS creates the target schema objects necessary to perform the migration. However, AWS DMS takes a minimalist approach and creates only those objects required to efficiently migrate the data. In other words, AWS DMS creates tables, primary keys, and in some cases unique indexes, but it doesn't create any other objects that are not required to efficiently migrate the data from the source. For example, it doesn't create secondary indexes, non-primary key constraints, or data defaults.
>
>In most cases, when performing a migration, you will also want to migrate most or all of the source schema. If you are performing a homogeneous migration (between two databases of the same engine type), you migrate the schema by using your engine’s native tools to export and import the schema itself, without any data.

**Comment by whit537** [comment]
Right. So, that's a mess.

**Comment by whit537** [comment]
Squashed and rebased, was 870cc861970303f0e9fb1a3a953515d44d4baf5d.

**Comment by whit537** [comment]
PR in https://github.com/capitalone/cloud-custodian/pull/1051.

**Pull request closed without merging**
