### PR TITLE
[-v] Add future imports

### PR DESCRIPTION
**Pull request by whit537**
Verbose log for https://github.com/capitalone/cloud-custodian/pull/1214, a step toward https://github.com/capitalone/cloud-custodian/issues/705.

### CODE REVIEW

**Comment by whit537** [comment]
I started adding these manually but then hit the resources directory. Writing a script.

**Comment by whit537** [comment]
Alright, five test failures with 587e296d6078a98c9f58de6588c7749ca55d6393.

Here's [the script](https://gist.github.com/whit537/6b57726c915d21997c25813e4b6b3108) I used for the rough cut.

**Comment by whit537** [comment]
Fixed the one in `test_utils.py` in 2cff2a30607f4c6948d045f4932149b2467b75ea. Now what's up with offhours?

**Comment by whit537** [comment]
Differences in `u''.translate` vs. `b''.translate`.

```
(cloud-custodian) $ py.test tests/test_offhours.py -k test_schedule_parser
============================================ test session starts =============================================
platform darwin -- Python 2.7.12, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/whit537, inifile: pytest.ini
plugins: xdist-1.15.0, cov-2.4.0
collected 25 items 

tests/test_offhours.py 
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB set_trace (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/filters/offhours.py(511)parse_resource_schedule()
-> exprs = lexeme.translate(None, '[]').split(',(')
(Pdb) lexeme
u'(m-f,10)'
(Pdb) !b'foo'.translate(None, '[]')
'foo'
(Pdb)
```

**Comment by whit537** [comment]
https://docs.python.org/2/library/stdtypes.html#str.translate

**Comment by whit537** [comment]
Squashed. How about tools, etc.?

**Comment by whit537** [comment]
Looking at `tests` ... [26 failures](https://gist.github.com/whit537/b7d9ddaa72b484c43aec70bb6375f665) after basic cleanups.

**Comment by whit537** [comment]
Down to three.

**Comment by whit537** [comment]
Down to one.

**Comment by whit537** [comment]
Hmm ... no output from cli test.

**Comment by whit537** [comment]
Sike!

```

2017-05-22 07:31:14,441: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 261, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/ec2.py", line 91, in resources
    return super(EC2, self).resources(query=query)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py", line 290, in resources
    resources = self.augment(self.source.resources(query))
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py", line 151, in resources
    self.query.filter, self.manager.resource_type, **query)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/utils.py", line 328, in _retry
    return func(*args, **kw)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py", line 63, in filter
    data = results.build_full_result()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/paginate.py", line 438, in build_full_result
    for response in self:
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/paginate.py", line 249, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/paginate.py", line 321, in _make_request
    return self._method(**current_kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: Authorization header or parameters are not formatted correctly.
2017-05-22 07:31:14,442: custodian.commands:ERROR Error while executing policy will-never-run, continuing
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/commands.py", line 210, in run
    policy()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 624, in __call__
    return mode.run()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/policy.py", line 261, in run
    resources = self.policy.resource_manager.resources()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/resources/ec2.py", line 91, in resources
    return super(EC2, self).resources(query=query)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py", line 290, in resources
    resources = self.augment(self.source.resources(query))
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py", line 151, in resources
    self.query.filter, self.manager.resource_type, **query)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/utils.py", line 328, in _retry
    return func(*args, **kw)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py", line 63, in filter
    data = results.build_full_result()
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/paginate.py", line 438, in build_full_result
    for response in self:
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/paginate.py", line 249, in __iter__
    response = self._make_request(current_kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/paginate.py", line 321, in _make_request
    return self._method(**current_kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 557, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (AuthFailure) when calling the DescribeInstances operation: Authorization header or parameters are not formatted correctly.

```

**Comment by whit537** [comment]
```
(Pdb) l
134     
135         def __repr__(self):
136             return '%s(%s)' % (self._endpoint_prefix, self.host)
137     
138         def make_request(self, operation_model, request_dict):
139  ->         logger.debug("Making request for %s (verify_ssl=%s) with params: %s",
140                          operation_model, self.verify, request_dict)
141             return self._send_request(request_dict, operation_model)
142     
143         def create_request(self, params, operation_model=None):
144             request = create_request_object(params)
(Pdb) pp request_dict
{'body': {'Action': u'GetCallerIdentity', 'Version': u'2011-06-15'},
 'context': {'auth_type': None,
             'client_config': <botocore.config.Config object at 0x108858bd0>,
             'client_region': 'us-west-2',
             'has_streaming_input': False},
 'headers': {'User-Agent': 'Boto3/1.4.4 Python/2.7.12 Darwin/14.5.0 Botocore/1.5.46'},
 'method': u'POST',
 'query_string': '',
 'url': u'https://sts.amazonaws.com/',
 'url_path': '/'}
(Pdb)
```

**Comment by whit537** [comment]
Is that `'auth_type`: None` bad?

**Comment by whit537** [comment]
Gosh, this is curious. I thought it might be due to a region mismatch in my config (as I seem to recall hitting when running the full test suite for the first time recently), but no.

I also can't see that it is in fact that a "[parameter was not set in aws configure](http://thecoatlessprofessor.com/programming/configuring-aws-cli/)."

**Comment by whit537** [comment]
Alright, let's get a delta going here. What change introduced the regression?

**Comment by whit537** [comment]
Waaaaaiiit a sec ... also failing on `master`?! Sure this isn't the same config issue we hit before?

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/commit/151998692ce4d2e6ef691f4e066d0f72346dcabd looks suspicious.

**Comment by whit537** [comment]
Yup, that was it. :roll_eyes: 

```
(cloud-custodian) $ py.test tests/test_cli.py -k test_failure_with_no_default_region
============================================ test session starts =============================================
platform darwin -- Python 2.7.12, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/whit537, inifile: pytest.ini
plugins: xdist-1.15.0, cov-2.4.0
collected 20 items 

tests/test_cli.py .

============================================ 19 tests deselected =============================================
================================== 1 passed, 19 deselected in 1.12 seconds ===================================
(cloud-custodian) $ cat ~/.aws/config 
[default]
(cloud-custodian) $
```

But didn't I put that in there to get a different test to pass? Am I forked?

**Comment by whit537** [comment]
¯\\\_(ツ)\_/¯

```
================================== 612 passed, 1 skipped in 157.92 seconds ===================================
```

**Comment by whit537** [comment]
That's master. Recheck branch.

**Comment by scotwk** [comment]
@whit537 - just saw this, and I figured out the problem with that test I added.  It will pass every time on the build server, but it is faulty when running on a developer machine depending on your environment.  It will fail if you have a default set in `~/.aws/config` which is likely true for everyone - although I had disabled mine locally while working on this.

I'll work on a fix, but in the meantime just ignore it.

**Comment by scotwk** [comment]
@whit537 - fix provided on https://github.com/capitalone/cloud-custodian/pull/1213

Sorry!

**Comment by whit537** [comment]
For your good deed of reporting here on this ticket, I shall now punish you with a torrent of miscellany and obfuscatia. 😈

**Comment by whit537** [comment]
Rerunning on branch.

**Comment by whit537** [comment]
💃

```
================================== 612 passed, 1 skipped in 138.32 seconds ===================================
```

**Comment by whit537** [comment]
Actually, you caught me at the end here. Not very much of a torrent left. :P

**Comment by whit537** [comment]
... because I don't trust updating the tools here, since they're untested (manually tested). On the other hand, I don't trust this PR _without_ manually testing the tools (I have runscripts for mailer and sentry), so I may as well upgrade those two.

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_mailer/#tutorial
https://github.com/capitalone/cloud-custodian/tree/master/tools/c7n_sentry/#custodian-sentry-integration

**Comment by whit537** [comment]
Tightening up my testeroos.tbz.

**Comment by whit537** [comment]
Published okay. What does the log say?

```
(cloud-custodian) $ c7n-mailer -c mailer.yml && custodian run -c test-policy.yml -s .
2017-05-23 06:32:34,660 - custodian.lambda - DEBUG - Created custodian lambda archive size: 3.01mb
2017-05-23 06:32:35,730 - custodian.lambda - INFO - Publishing custodian policy lambda function cloud-custodian-mailer
2017-05-23 06:32:53,188 - custodian.lambda - DEBUG - Added lambda invoke cwe rule permission
2017-05-23 06:32:53,311 - custodian.lambda - DEBUG - Creating cwe rule target for <CWEvent Type:periodic Events:> on func:arn:aws:lambda:us-west-2:644160558196:function:cloud-custodian-mailer
2017-05-23 06:32:53,441 - custodian.lambda - DEBUG - Added event source: <CWEvent Type:periodic Events:> to function: arn:aws:lambda:us-west-2:644160558196:function:cloud-custodian-mailer
Error: No default region set. Specify a default via AWS_DEFAULT_REGION or setting a region in ~/.aws/config
(cloud-custodian) $
```

**Comment by whit537** [comment]
Oops, need that region here. ☺️

**Comment by whit537** [comment]
S'better.

```
(cloud-custodian) $ c7n-mailer -c mailer.yml && custodian run -c test-policy.yml -s .
2017-05-23 06:35:12,090 - custodian.lambda - DEBUG - Created custodian lambda archive size: 3.01mb
2017-05-23 06:35:14,138 - custodian.lambda - DEBUG - Updating function: cloud-custodian-mailer config
2017-05-23 06:35:23,681: custodian.policy:INFO policy: c7n-mailer-test resource:sqs region:us-west-2 count:1 time:1.47
2017-05-23 06:35:25,067: custodian.actions:INFO sent message:27e0d42e-c60f-4d2d-920f-fcd244d55413 policy:c7n-mailer-test template:default count:1
2017-05-23 06:35:25,067: custodian.policy:INFO policy: c7n-mailer-test action: notify resources: 1 execution_time: 1.39
(cloud-custodian) $ cat ~/.aws/config 
[default]
region=us-east-1
region=us-west-2
(cloud-custodian) $
```

**Comment by whit537** [comment]
```
Unable to import module 'periodic': No module named sqs_message_processor
```

**Comment by whit537** [comment]
`Unable to import module 'periodic': No module named address`

**Comment by whit537** [comment]
`Syntax error in module 'periodic': invalid syntax (record.py, line 151)`

**Comment by whit537** [comment]
`Unknown resource type sqs` ... but that might be normal?

**Comment by whit537** [comment]
Yeah, it's working.

**Comment by whit537** [comment]
Sentry also working.

**Comment by whit537** [comment]
Hitting some floofy Travis problems. First flake8, easy enough. Now consistently [getting](https://travis-ci.org/capitalone/cloud-custodian/builds/235987062#L1370-L1371) `test_logsub.py` failure+error. Hmm ... :thinking:

**Comment by whit537** [comment]
I'm not seeing this locally. And we didn't see it before when we were just getting a flake8 fail.

**Comment by whit537** [comment]
Asked to remove from empty files and version.py.

Not sure why Travis [failed](https://travis-ci.org/capitalone/cloud-custodian/builds/235987062) on https://github.com/capitalone/cloud-custodian/commit/b95852dc6d191edb681917e1f37a250c4d9e94c0, and then ... disappeared?!

screen shot 2017-05-26 at 4 15 44 am

**Comment by whit537** [comment]
Hmm ... squashed and conflicts resolved and now building on Travis again ...

**Comment by whit537** [comment]
... and it [passes](https://travis-ci.org/capitalone/cloud-custodian/builds/236297300)! O.o

**Pull request closed without merging**
