### PR TITLE
[-v] Implement a datapipeline resource

### PR DESCRIPTION
**Pull request by whit537**
Aimed at https://github.com/capitalone/cloud-custodian/issues/909. PR is here in my fork for verbose logging, will remake against upstream once the dust settles.

### Todo

- [ ] Implement resource class for reporting

### CODE REVIEW

**Comment by kapilt** [comment]
datapipe?

**Comment by whit537** [comment]
Per call, I will focus on the base resource descriptor for an initial PR, leaving filters/actions for down the line.

**Comment by kapilt** [comment]
filters for and, or, value are for free. the tag filters/actions typically come via subclassing the bases in tags.py.  lots of extant examples.

**Comment by whit537** [comment]
Squashed and rebased on latest `master`. Proceeding to unravel extra rough-in ...

**Comment by whit537** [comment]
If needed for parts in the future: 64ba75ca3c43607473974c8ab752497923ddda34.

**Comment by whit537** [comment]
Alright, what's the test here? Had been testing delete, now just want reporting ...

**Comment by whit537** [comment]
Create doesn't seem to be working in 49c08335d1034ab009785610fa0685050e82ca4c. I run the test and don't find a corresponding object in the console (no data pipelines whatsoever). Creating seems to be a complicated process (shell command `grep`?!).

screen shot 2017-03-01 at 3 36 54 am

**Comment by whit537** [comment]
And yet the `CreatePipeline` placebo json shows a 200 with a `pipelineId`. What gives?

```
{
    "status_code": 200, 
    "data": {
        "pipelineId": "df-07567962IEYCDYFC4IGS", 
        "ResponseMetadata": {
            "RetryAttempts": 0, 
            "HTTPStatusCode": 200, 
            "RequestId": "932c7f86-fe59-11e6-b9c7-818ae0157aa6", 
            "HTTPHeaders": {
                "x-amzn-requestid": "932c7f86-fe59-11e6-b9c7-818ae0157aa6", 
                "date": "Wed, 01 Mar 2017 08:32:15 GMT", 
                "content-length": "40", 
                "content-type": "application/x-amz-json-1.1"
            }
        }
    }
}
```

**Comment by whit537** [comment]
Hmmm ... [looks like](http://boto3.readthedocs.io/en/latest/reference/services/datapipeline.html) activate is a different activity than create ...

**Comment by whit537** [comment]
f44e2cc59d3949de4397e8b3b5fd93e8595a0758

```
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_datapipeline.py", line 27, in test_reporting
    response = client.activate_pipeline(pipelineId=pipeline['pipelineId'])
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidRequestException) when calling the ActivatePipeline operation: Pipeline definition is empty: 
```

**Comment by whit537** [comment]
http://boto3.readthedocs.io/en/latest/reference/services/datapipeline.html#DataPipeline.Client.put_pipeline_definition

**Comment by whit537** [comment]
Seeing a couple [examples](https://docs.aws.amazon.com/datapipeline/latest/APIReference/API_PutPipelineDefinition.html) but no real docs on definition format for put. I guess we start smashing ... can at least get fields requirements from Console UI?

**Comment by whit537** [comment]
```
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_datapipeline.py", line 27, in test_reporting
    response = client.put_pipeline_definition(pipelineId=pipeline['pipelineId'])
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 513, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 566, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Missing required parameter in input: "pipelineObjects"
```

**Comment by whit537** [comment]
Same as https://github.com/whit537/cloud-custodian/pull/3#issuecomment-283281681 in fb07f90bc2345b8780056b12da1ca3886058e533.

**Comment by whit537** [comment]
S'good?

```
(Pdb) pp response
{'ResponseMetadata': {'HTTPHeaders': {'content-length': '421',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Wed, 01 Mar 2017 10:03:08 GMT',
                                      'x-amzn-requestid': '4514d01e-fe66-11e6-90ed-1f399d793de2'},
                      'HTTPStatusCode': 200,
                      'RequestId': '4514d01e-fe66-11e6-90ed-1f399d793de2',
                      'RetryAttempts': 0},
 u'errored': False,
 u'validationErrors': [],
 u'validationWarnings': [{u'id': u'SayHello',
                          u'warnings': [u" It is recommended to set 'failureAndRerunMode'  to 'cascade' on Default object to enable cascade failure mode for Activity, Datanode, Precondition and Resource objects of a pipeline."]},
                         {u'id': u'Default',
                          u'warnings': [u"'pipelineLogUri'is missing. It is recommended to set this value on Default object for better troubleshooting."]}]}
(Pdb)
```

**Comment by whit537** [comment]
Hah! Found it in the right region. 😊 

And it's activating properly!

screen shot 2017-03-01 at 5 06 19 am

**Comment by whit537** [comment]
Alright, now to find it via policy.

```
(Pdb) l
 49                 'name': 'datapipeline-report',
 50                 'resource': 'datapipeline'},
 51                 session_factory=factory)
 52             resources = p.run()
 53             import pdb; pdb.set_trace()
 54  ->         self.assertEqual(len(resources), 1)
 55             self.assertEqual(resources[0]['DataPipelineName'], 'PipelinesFTW')
[EOF]
(Pdb) resources
[]
(Pdb)
```

**Comment by whit537** [comment]
Actually, also having trouble deleting it on cleanup ...

**Comment by whit537** [comment]
Latest in9037c19380b3268c85700b54b90a8498cacb9c06.

**Comment by whit537** [comment]
False alarm. Deleting is working fine.

screen shot 2017-03-01 at 5 30 57 am

Okay! Reporting!

**Comment by whit537** [comment]
Huh. Region mismatch, eh?

```
(Pdb) l
268                 perms.extend(self.permissions)
269             return perms
270     
271         def resources(self, query=None):
272             import pdb; pdb.set_trace()
273  ->         key = {'region': self.config.region,
274                    'resource': str(self.__class__.__name__),
275                    'q': query}
276     
277             if self._cache.load():
278                 resources = self._cache.get(key)
(Pdb) self.config.region
'us-east-1'
(Pdb)
```

**Comment by whit537** [comment]
If I add `'region': 'us-west-2'` to the policy definition, then i don't hit the breakpoint?

**Comment by whit537** [comment]
D'oh! Worth a try. ;-)

```
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_datapipeline.py", line 57, in test_reporting
    session_factory=factory)
TypeError: load_policy() got an unexpected keyword argument 'region'
```

**Comment by whit537** [comment]
Set `region` in the `session_factory` call?

**Comment by whit537** [comment]
Drat. Not it either.

```
(Pdb) l
272             key = {'region': self.config.region,
273                    'resource': str(self.__class__.__name__),
274                    'q': query}
275             import pdb; pdb.set_trace()
276     
277  ->         if self._cache.load():
278                 resources = self._cache.get(key)
279                 if resources is not None:
280                     self.log.debug("Using cached %s: %d" % (
281                        "%s.%s" % (
282                             self.__class__.__module__,
(Pdb) self.config.region
'us-east-1'
(Pdb)
```

**Comment by whit537** [comment]
[Got it](https://github.com/whit537/cloud-custodian/blob/2b2f3770df4919a52fd032c1efbf00dfdf502fa0/tests/test_redshift.py#L152). 👍 

```
(Pdb) self.config.region
'us-west-2'
(Pdb)
```

**Comment by whit537** [comment]
`ListPipelines` is still coming up empty, even though I see pipelines in the console. Hmm ... :thinking:

screen shot 2017-03-03 at 5 08 04 am

```
(Pdb) l
285                     return self.filter_resources(resources)
286     
287             if query is None:
288                 query = {}
289     
290  ->         resources = self.augment(self.source.resources(query))
291             self._cache.save(key, resources)
292             return self.filter_resources(resources)
293     
294         def get_resources(self, ids, cache=True):
295             key = {'region': self.config.region,
(Pdb) n
2017-03-03 05:07:25,330 - placebo.pill - DEBUG - _create_client
2017-03-03 05:07:25,836 - placebo.pill - DEBUG - _record_data
2017-03-03 05:07:25,837 - placebo.pill - DEBUG - save_response: datapipeline.ListPipelines
2017-03-03 05:07:25,837 - placebo.pill - DEBUG - get_new_file_path: datapipeline.ListPipelines
2017-03-03 05:07:25,838 - placebo.pill - DEBUG - save_response: path=/Users/whit537/workbench/capitalone/cloud-custodian/tests/data/placebo/test_datapipeline_reporting/datapipeline.ListPipelines_2.json
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(291)resources()
-> self._cache.save(key, resources)
(Pdb) resources
[]
(Pdb)
```

**Comment by whit537** [comment]
Something needed with augment?

**Comment by whit537** [comment]
Definitely getting pipelines back from the API:

```
(Pdb) l
 54             if extra_args:
 55                 params.update(extra_args)
 56     
 57             if client.can_paginate(enum_op):
 58                 p = client.get_paginator(enum_op)
 59  ->             results = p.paginate(**params)
 60                 data = results.build_full_result()
 61             else:
 62                 op = getattr(client, enum_op)
 63                 data = op(**params)
 64             if path:
(Pdb) params
{}
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(60)filter()
-> data = results.build_full_result()
(Pdb) results
<botocore.paginate.PageIterator object at 0x111602050>
(Pdb) n
2017-03-03 05:14:55,913 - placebo.pill - DEBUG - _record_data
2017-03-03 05:14:55,914 - placebo.pill - DEBUG - save_response: datapipeline.ListPipelines
2017-03-03 05:14:55,914 - placebo.pill - DEBUG - get_new_file_path: datapipeline.ListPipelines
2017-03-03 05:14:55,917 - placebo.pill - DEBUG - save_response: path=/Users/whit537/workbench/capitalone/cloud-custodian/tests/data/placebo/test_datapipeline_reporting/datapipeline.ListPipelines_1.json
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(64)filter()
-> if path:
(Pdb) pp data
{u'pipelineIdList': [{u'id': u'df-09857702PYHKMJJ72ERP',
                      u'name': u'PipelinesFTW'},
                     {u'id': u'df-09368632A2S340T5X711',
                      u'name': u'PipelinesFTW'}]}
(Pdb)
```

**Comment by whit537** [comment]
Bad jmespath filter.

```
(Pdb) l
 59                 results = p.paginate(**params)
 60                 data = results.build_full_result()
 61             else:
 62                 op = getattr(client, enum_op)
 63                 data = op(**params)
 64  ->         if path:
 65                 path = jmespath.compile(path)
 66                 data = path.search(data)
 67             if data is None:
 68                 data = []
 69             return data
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(65)filter()
-> path = jmespath.compile(path)
(Pdb) path
'DataPipelineGroups'
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(66)filter()
-> data = path.search(data)
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(67)filter()
-> if data is None:
(Pdb) pp data
None
(Pdb)
```

**Comment by whit537** [comment]
Alright, I'm past the jmespath boss, but not out of the woods.

```
(Pdb) l
 60                 data = results.build_full_result()
 61             else:
 62                 op = getattr(client, enum_op)
 63                 data = op(**params)
 64             import pdb; pdb.set_trace()
 65  ->         if path:
 66                 path = jmespath.compile(path)
 67                 data = path.search(data)
 68             if data is None:
 69                 data = []
 70             return data
(Pdb) path
'pipelineIdList'
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(66)filter()
-> path = jmespath.compile(path)
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(67)filter()
-> data = path.search(data)
(Pdb) path
{'type': 'field', 'children': [], 'value': u'pipelineIdList'}
(Pdb) data
{u'pipelineIdList': [{u'id': u'df-00211801LQAJBMGG19OR', u'name': u'PipelinesFTW'}]}
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/query.py(68)filter()
-> if data is None:
(Pdb) data
[{u'id': u'df-00211801LQAJBMGG19OR', u'name': u'PipelinesFTW'}]
(Pdb)
```

**Comment by whit537** [comment]
Now for the self.filter boss.

```
(Pdb) l
286     
287             if query is None:
288                 query = {}
289     
290             resources = self.augment(self.source.resources(query))
291  ->         self._cache.save(key, resources)
292             return self.filter_resources(resources)
293     
294         def get_resources(self, ids, cache=True):
295             key = {'region': self.config.region,
296                    'resource': str(self.__class__.__name__),
(Pdb) resources
[{u'id': u'df-00819242Q7L7CZWYYY8O', u'name': u'PipelinesFTW'}, {u'id': u'df-00211801LQAJBMGG19OR', u'name': u'PipelinesFTW'}]
(Pdb) self.filter_resources(resources)
[]
(Pdb)
```

**Comment by whit537** [comment]
`ValueFilter` boss.

```
(Pdb) l
 82                     "Filtering resources with %s", self.filters)
 83             for f in self.filters:
 84                 if not resources:
 85                     break
 86                 rcount = len(resources)
 87  ->             resources = f.process(resources, event)
 88                 if event and event.get('debug', False):
 89                     self.log.debug(
 90                         "applied filter %s %d->%d", f, rcount, len(resources))
 91             self.log.debug("Filtered from %d to %d %s" % (
 92                 original, len(resources), self.__class__.__name__.lower()))
(Pdb) n
> /Users/whit537/workbench/capitalone/cloud-custodian/c7n/manager.py(88)filter_resources()
-> if event and event.get('debug', False):
(Pdb) resources
[]
(Pdb) self.filters
[<c7n.filters.core.ValueFilter object at 0x10799d650>]
(Pdb)
```

**Comment by whit537** [comment]
[... is jmespath boss again!](https://github.com/capitalone/cloud-custodian/blob/2b2f3770df4919a52fd032c1efbf00dfdf502fa0/c7n/filters/core.py#L242-L244)

**Comment by whit537** [comment]
[`filter_{name,type}`](https://github.com/capitalone/cloud-custodian/blob/2b2f3770df4919a52fd032c1efbf00dfdf502fa0/c7n/resources/datapipeline.py#L30-L31)?

**Comment by whit537** [comment]
`DataPipelineName` is used in several places. Is that right?

**Comment by whit537** [comment]
`acm` uses a `list_` `enum_spec`, and [_has_](https://github.com/capitalone/cloud-custodian/blob/2b2f3770df4919a52fd032c1efbf00dfdf502fa0/c7n/resources/acm.py#L22-L32) no `filter_*`!

**Comment by whit537** [comment]
Moving to PR in https://github.com/capitalone/cloud-custodian/pull/1003.

**Pull request closed without merging**
